### Requête pour enregistrer un nouvel utilisateur
POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "id": 0,
  "firstname": "John",
  "lastname": "Doe",
  "email": "john.doe@gmail.com",
  "password": "securepassword123"
}

### Requête pour connecter un utilisateur existant
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@gmail.com",
  "password": "securepassword123"
}

### Requête pour récupérer les informations de l'utilisateur connecté
GET http://localhost:3000/users/me HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6MjAwLCJpYXQiOjE3NjI4MDM2MTUsImV4cCI6MTc2MjgwNzIxNX0.TT4d0RFn9YkcEa8vd_TmtPUoozcBy0PN9qrPQ9Qf_4w

### Requête pour récupérer la liste de tous les utilisateurs (accessible uniquement aux administrateurs)
GET http://localhost:3000/users/all-users HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6MjAwLCJpYXQiOjE3NjI4MDM2MTUsImV4cCI6MTc2MjgwNzIxNX0.TT4d0RFn9YkcEa8vd_TmtPUoozcBy0PN9qrPQ9Qf_4w